force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <label>Module Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Units completed</label>
    <summaryFilterItems>
        <field>Unit_Response__c.Completed__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Unit_Response__c.Module_Response__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Quest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unity__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions Responses</relationshipLabel>
    <relationshipName>Questions_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question Response</relationshipLabel>
    <relationshipName>Questions_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Module_Response__c.field-meta.xml
<CustomField>
    <fullName>Module_Response__c</fullName>
    <label>Module Response</label>
    <referenceTo>Module_Response__c</referenceTo>
    <relationshipLabel>Unit Response</relationshipLabel>
    <relationshipName>Units_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Draft : Apenas creamos el registro, este estado existe. Hasta que no creemos los registros relacionados con las preguntas y opciones marcadas no podremos evaluarlo. Por eso, necesitamos este primer estado. Una vez que terminemos de crear los registros relacionados con las respuestas a las preguntas podremos pasarlo de estado.

Answered : Se pasará a este estado una vez que hayamos terminado de cargar todas las respuestas para esa unidad.

Success : Caeremos en este estado una vez verificado el resultado y que el mismo sea correcto.

Fail : En el caso de que alguna de las preguntas haya sido respondida incorrectamente.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Tries__c.field-meta.xml
<CustomField>
    <fullName>Tries__c</fullName>
    <label>Tries</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unity__c</referenceTo>
    <relationshipLabel>Units Responses</relationshipLabel>
    <relationshipName>Units_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public class UnitService {
    public class WrongDataException extends Exception {}

    public static Boolean UnitService(Id unitId, String JsonAnswer) {

        Savepoint sp = Database.setSavepoint();

        try{
            Id UserId = UserInfo.getUserId();
            Unit__c Unit = [ 
                SELECT Module__c,  
                (SELECT Id, Tries__c FROM Units_Responses__r WHERE Module_Response__r.User__c =: UserId ORDER BY Tries__c DESC LIMIT 1), 
                (SELECT Id, Name FROM Questions__r)
                FROM Unit__c WHERE Id = :unitId
            ];
            Module_Response__c Mresponse = [SELECT Id FROM Module_response__c WHERE (Module__c =: Unit.Module__c AND User__c =: UserId)];
                
            if(Mresponse == null){
                MResponse = new Module_Response__c(
                    User__c = UserId, 
                    Module__c = Unit.Module__c, 
                    Status__c = 'In progress'
                );
                insert MResponse;
            }
    
            Unit_Response__c UResponse = new Unit_Response__c(
                State__c = 'Draft',
                Unit__c = unitId,
                Module_Response__c = MResponse.Id
            );
            UResponse.Tries__c = !unit.Units_Responses__r.isEmpty() ? unit.Units_Responses__r[0].Tries__c + 1 : 1;
            insert UResponse;
    
            Map<Id, Id> AnswerMap = (Map<Id, Id>)JSON.deserializeStrict(JsonAnswer, Map<Id,Id>.class);
            List<Question_Response__c> QuestionRespList = new List<Question_Response__c>();
    
            for(Question__c question : unit.Questions__r){
                if(AnswerMap.containsKey(question.Id)){
                Question_Response__c questionResp = new Question_Response__c(
                    Question__c = question.Id,
                    Unit_Response__c = UResponse.id,
                    Option__c = AnswerMap.get(question.Id)
                );
                QuestionRespList.add(questionResp);
                }
                else{
                    throw new WrongDataException('La pregunta ' + question.Name + ' no fue respondida y es requerida.');
                }
            }
            insert QuestionRespList;
            UResponse.State__c = 'Answered';
            update UResponse;
        }catch(WrongDataException e){
            Database.rollback(sp);
            throw e;

        }
        return True;
    }
}